### ISSUE TITLE
[Sampler] Possible extensions

### ISSUE THREAD

**Issue by jmidt** [topisani/OTTO#102]
These are some things that would be nice to have, but are not crucial for a first implementation.

- Velocity sensitivity. This can be both simple velocity sensitivity in volume. But could also be a dynamic change of sample file, depending on the velocity, if you for instance have a sampled piano with several different velocities for each note.

- Sample copying. The ability to copy the data from one sample slot/note to another. 

- Automatic sample allocation: If you for instance have a sampled piano and you choose one note from it, there could be a possibility of automatically laying out the other samplles in the corresponding slots. This would require some specific naming scheme to be followed for the sample files.

**Comment by topisani** [comment]
Closing this, as:
Velocity sensitivity is in
Sample copying will be part of a larger copy/paste system I've been thinking about
Automatic allocation only makes sense for a melodic sampler, which we don't have yet
