### ISSUE TITLE
Wiki outdated: building needs GCC 9+

### ISSUE THREAD

**Issue by thomasbbrunner** [topisani/OTTO#123]
Hi! New here, sorry if this is not the right place to post this.

The wiki states that the minimum GCC version needed to compile is gcc 7.2.
(https://github.com/topisani/OTTO/wiki/Compiling-and-Running) 

I tried to build using version 7.4, but got an error when compiling magic_enum.hpp. Their Github page state the need for gcc 9+.
(https://github.com/Neargye/magic_enum)

Building with clang 6.0 worked though.

Could we get the wiki updated?

**Comment by nosleepbeats** [comment]
Had the same issue running gcc 7.4. I’ll try with 9+. What version of Ubuntu were you using?

**Comment by thomasbbrunner** [comment]
Hey, I am using Ubuntu 18.04.

**Comment by topisani** [comment]
Use clang for now.

I'll remove magic_enum again eventually
