### ISSUE TITLE
Project rename

### ISSUE THREAD

**Issue by topisani** [topisani/OTTO#14]
There are quite a few reasons why we need to rename the TOP-1.
First of all, i don't know if you noticed, but its just OP-1 with a T in front. It would be nice to have something completely different, both to not infringe on any trademarks, and to change the perception of this project as a direct clone of the OP-1.
Other than that, its a Totally Obnoxious Project name, and we need something better.

There has been quite a bit of discussion in the discord chat, and we have looked at funny, contrived, clever and stupid acronyms like `HAROLD - Has Anyone Really Overtaken Loud Doctors?`.
I am not sure an acronym like that is really the way to go, even if its better than HAROLD, but lets hear some suggestions.

Personally, i kinda like `Arienette`, but [id prefer not to talk about it, in case she's listening](https://youtu.be/LQAK4r5fxRY?t=4m22s)

Lets hear all the ideas down below ↓↓↓↓

Edit: Ideas im currently most fond of:
```
OTTO
Arienette
Kenopi (KenoPi ?)
```

**Comment by VelocityRa** [comment]
Someone on Discord had suggested **Q.U.A.R.K** (**QU**ad **A**rrangement & **R**ecording **K**ernel).

**Comment by sastani** [comment]
I also suggested R.A.L.P.H. Or Really Awesome Little Piece of Hardware

**Comment by rghvdberg** [comment]
BOSSE: Best Open Source Software Ever

**Comment by sastani** [comment]
I like BOSSE
Or BOSSé

**Comment by thedaniel** [comment]
BOSSE is cute but it reminds me of BOSS, Roland's guitar effects brand

**Comment by thedaniel** [comment]
I actually also like Arienette, I know it's a Bright Eyes reference, but it sounds sort of small and delicate and Euro and particular, kinda like the OP-1

**Comment by topisani** [comment]
@thedaniel thats exactly why i like it

on discord we talked about `OP-1 Kenobi` and from there just `Kenobi` or `Kenopi`. And while thats funny, im not sure a star wars reference is the best way to go

**Comment by simonvanderveldt** [comment]
Kenopi One (or 1?) sounds pretty nice though! :P

**Comment by rghvdberg** [comment]
Opi one kenopi! Lol

**Comment by rosshardy** [comment]
If you google. OP1Kenobi you can see there is already someone/some people using that name for various OP-1 things. 

What about something related to open source? Like “OS-1”? Or “OS-OP1”?

**Comment by topisani** [comment]
@rosshardy well i think `Kenopi` is what we would go with in that direction - we dont want the name to contain OP-1

**Comment by sastani** [comment]
OSHE = Open Source Hardware Emulation?

or

OSHI = Open Source Hardware Interface? (was thinking of yoshi when this came up)

**Comment by sastani** [comment]
R.A.L.P.H. = Really Awesome Little Piece of Hardware

**Comment by D-I-S-K-U-S** [comment]
O,SHIT.

I still like 'Otto'. Not sure what it should stand for. Should it even stand for anything?
Perhaps its 'Otto-matic'. ;-)

**Comment by sastani** [comment]
I like OTTO too. Why dont we pick top 3 names and just do a vote?

**Comment by sastani** [comment]
Kenopi, Otto, Oshi?

**Comment by D-I-S-K-U-S** [comment]
_Arigato. Sorry, I don't speak Japanese._

**Comment by D-I-S-K-U-S** [comment]
Except if I were to get violent, then I'd _jab a niece_.

# **Dad-joke level over 9000.**

**Comment by VelocityRa** [comment]
@D-I-S-K-U-S That's terrible, nice.
@sastani No, this is just a place to post _ideas_, the final say is obviously @topisani's.

**Comment by sastani** [comment]
This is a group effort, hence why I say we vote...

**Comment by topisani** [comment]
Not a fan of OSHI, its too _jab-a-niece_
OTTO is nice, and i like it just meaning OTTOmatic

I do think we should just keep throwing ideas around for a bit, then ill pick something next week or so

**Comment by sastani** [comment]
What’s wrong with being jab-a-niece ;)

**Comment by Inscrutable** [comment]
I had suggested TOP-QUARK, and a few more, in the discord thread long ago. Here's a few more idle thoughts (in case there's been no decision yet):
4URA, InTune, LYRE, TetraPodium, F4vesser, AudioScribe, NICOLO, D-Box, 4D-Tuner, The Sonic Brick.

**Comment by topisani** [comment]
I think we're going with OTTO! I'll start a huge search/replace everywhere
