### ISSUE TITLE
Jack Issues on Sierra OSX (10.12)

### ISSUE THREAD

**Issue by sastani** [topisani/OTTO#25]
As of the last 2 commits, this is no longer a working version of OTTO on Sierra.

See attached file.
[errorlog.txt](https://github.com/topisani/OTTO/files/1448161/errorlog.txt)

**Comment by topisani** [comment]
this is an issue with your jack setup (as you state in the title). I don't think the OTTO has anything to do with this. I am not in any way an expert on jack, especially on OSX, but it seems OTTO can't find a physical input port, which it needs to run. Maybe jack i using the wrong sound interface?

**Comment by sastani** [comment]
Yeah, I got it working. Combination of my jack setup as well as the drum sample I was using was a 16 bit wav.
