### ISSUE TITLE
Visualization of performance data

### ISSUE THREAD

**Issue by topisani** [topisani/OTTO#27]
OTTO records performance data to a json file in `data/timers.json` in debug builds. It would be great to be able to analyze this data, maybe draw some graphs, or even have an interactive js visualization.

Using travis, this could be built for each commit, and pushed to a webpage.

For reference, this is the interface for recording data:
https://github.com/topisani/OTTO/blob/master/src/util/timer.hpp

**Comment by hox3d** [comment]
Just saw this, is it still needed?
For instance, would a python script work in that case?
