### ISSUE TITLE
Unfinished UI / UI Ideas.

### ISSUE THREAD

**Issue by D-I-S-K-U-S** [topisani/OTTO#36]
**_Well hi there._**

Here's a bunch of UI stuff I made, some unused, some trashed, some work in progress.

Feel free to share any (new) ideas and thoughts on the following UI ideas.
New purposes for old ideas and/or UI are also more than welcome.

Here they are with some minor explanations:

— _Any kind of distortion_
<img width="478" alt="schermafbeelding 2017-11-29 om 21 11 37" src="https://user-images.githubusercontent.com/31598745/33397112-ec208d0c-d54a-11e7-9d5a-d6a95f540e56.png">

— _the Blob._ : Might actually be finished this way, but room for change.
<img width="477" alt="schermafbeelding 2017-11-29 om 21 11 43" src="https://user-images.githubusercontent.com/31598745/33397137-fc5d516e-d54a-11e7-9ca0-01e1385c3dce.png">

— _Tornado_ : Would be for a synth, where the different circles can change in 'floating' height (so in first, all circles would align).
<img width="475" alt="schermafbeelding 2017-11-29 om 21 11 48" src="https://user-images.githubusercontent.com/31598745/33397157-11b14674-d54b-11e7-914f-310947e02bfe.png">

— _Kind of a glitchy synth, where you make points on various lines move around, so shapes emerge and go._
<img width="474" alt="schermafbeelding 2017-11-29 om 21 11 55" src="https://user-images.githubusercontent.com/31598745/33397195-3b9a5714-d54b-11e7-8cf2-a0b23d746cb7.png">

— _Tremolo of some kind; a bit too clear. As in, too self explanatory and not vague enough._
<img width="475" alt="schermafbeelding 2017-11-29 om 21 12 01" src="https://user-images.githubusercontent.com/31598745/33397223-55066a3a-d54b-11e7-8402-791cbe2ba43b.png">

— _Was initially for detuning, but thats a system setting and not an effect, so this screen is unnecessary. Could be cool for something else though. Based on DaVinci's work._
<img width="475" alt="schermafbeelding 2017-11-29 om 21 12 06" src="https://user-images.githubusercontent.com/31598745/33397248-684081d0-d54b-11e7-9b63-bf1ead1aca41.png">

— _Magnetic field synth._ : you move around the coloured dots, making the arrows react to the 'magnetic field' of those. In some positions you can make the arrows go wild and create total chaos.
<img width="476" alt="schermafbeelding 2017-11-29 om 21 12 11" src="https://user-images.githubusercontent.com/31598745/33397290-822c8828-d54b-11e7-8e33-cb5b256e617b.png">

— _Sacred Geometry synth_ : like the OP-1 equivelant with the dots and connected lines.
<img width="476" alt="schermafbeelding 2017-11-29 om 21 12 26" src="https://user-images.githubusercontent.com/31598745/33397327-a08d0860-d54b-11e7-818e-b3f6aaa0199f.png">

— _Initially for reverb or ambient room stuff, could be recycled for something_
<img width="478" alt="schermafbeelding 2017-11-29 om 21 13 10" src="https://user-images.githubusercontent.com/31598745/33397354-b283de7c-d54b-11e7-8530-9f2a303168fe.png">

— _Swimming Pool. Was gonna be for reverb._
<img width="480" alt="schermafbeelding 2017-11-29 om 21 13 26" src="https://user-images.githubusercontent.com/31598745/33397388-c3213036-d54b-11e7-83ab-ae2ca365dd16.png">

— _Compressor. Dont really like this one, bit like the tremolo. Needs revising._
<img width="476" alt="schermafbeelding 2017-11-29 om 21 14 32" src="https://user-images.githubusercontent.com/31598745/33397402-cec5b51a-d54b-11e7-9082-205e6be01c8e.png">

— _Drum Mic'er. This was gonna let you move the microphones around to shape the drum sounds._
<img width="477" alt="schermafbeelding 2017-11-29 om 21 14 38" src="https://user-images.githubusercontent.com/31598745/33397420-db587664-d54b-11e7-805b-c431ea713853.png">

— _Was gonna be for reverb. Quite like this one, could maybe be recycled for something. Rope was gonna have physics of some kind._
<img width="476" alt="schermafbeelding 2017-11-29 om 21 15 17" src="https://user-images.githubusercontent.com/31598745/33397453-f1d28c90-d54b-11e7-9f4a-d585d15d0847.png">

— _Was gonna be for delay. Found other UI for this purpose._
<img width="474" alt="schermafbeelding 2017-11-29 om 21 16 24" src="https://user-images.githubusercontent.com/31598745/33397474-04420f90-d54c-11e7-8db5-077d1ed86c49.png">

— _Some kind of level meter UI._
<img width="476" alt="schermafbeelding 2017-11-29 om 21 16 42" src="https://user-images.githubusercontent.com/31598745/33397494-1361dd02-d54c-11e7-9c02-260ad1e033eb.png">

— _EQ concept. Very weak, still pretty fun though._
<img width="479" alt="schermafbeelding 2017-11-29 om 21 17 11" src="https://user-images.githubusercontent.com/31598745/33397525-20674c44-d54c-11e7-856d-9e07200a2073.png">

— _Nuke synth._
<img width="476" alt="schermafbeelding 2017-11-29 om 21 31 39" src="https://user-images.githubusercontent.com/31598745/33397746-eb1d2f1c-d54c-11e7-9062-4f564426bcd3.png">

— _possible Tremolo/phaser UI_.
<img width="477" alt="schermafbeelding 2017-11-29 om 21 31 45" src="https://user-images.githubusercontent.com/31598745/33397752-f2841f54-d54c-11e7-87c6-857b4ede0cf4.png">

— _Reverb_.
<img width="478" alt="schermafbeelding 2017-11-29 om 21 31 51" src="https://user-images.githubusercontent.com/31598745/33397777-fb702e50-d54c-11e7-84cd-4c4cf61e1ca8.png">

— _Delay._
<img width="476" alt="schermafbeelding 2017-11-29 om 21 32 42" src="https://user-images.githubusercontent.com/31598745/33397783-02bc0b8e-d54d-11e7-877a-e17338a520b4.png">

**Comment by zacYP2** [comment]
this is great!

**Comment by D-I-S-K-U-S** [comment]
Thread closed because above images are using the 'old style'.
Please refer to UI Guidelines in the Wiki for the 'new style'.

Feel free to re-use or evolve on the above ideas.
