### ISSUE TITLE
TODO / Good places to start

### ISSUE THREAD

**Issue by topisani** [topisani/OTTO#42]
This should be a continuously updated list of things that need to be done, mainly on the c++ backend. Some of these are a good place to start contributing.

 - [ ] Add some useful information to the debug UI.
    This could also be a virtual keyboard, buttons, rotaries, etc

**Comment by D-I-S-K-U-S** [comment]
This thread is now obsolete as we refer to the alpha project page in this GitHub; and that works really well, and keeps everything neat and tidy.
