### ISSUE TITLE
Redesign/adjust audio processing

### ISSUE THREAD

**Issue by topisani** [topisani/OTTO#43]
Currently each engine owns at least one buffer, and references to these buffers are passed around in `ProcessData`. I feel like this is a fairly solid aproach, but with a few problems.
 - A lot of unneccessary copying between buffers, especially when faust is involved (take a look at `core/audio/faust.hpp`
 - A few syntactical problems in `main_audio`.

I feel like the best aproach in the OTTO style, would be to hand over a bit more control to `main_audio.cpp`, and make it more customizable from there.
So i propose passing an `out` buffer to `Engine::process` as well as an `in` buffer, and let the modules write directly to that. This out buffer then has runtime information, like whether audio should be added to it, or it can be overwritten, as well as which of its channels should be used.

Not sure i explained it perfectly, still gotta flesh it out completely in my head, but id like to hear any thoughts, questions and suggestions (@cbsrobot & @dacarley)

**Comment by harryhaaren** [comment]
Hi TopiSani,

Yes having buffers passed around is a good idea, a few notes from experience:
- Make sure it is obvious who owns the buffer
= If dynamically calling new/delete, consider using a ref-count to allow last-owner to free
== Have a GUI thread "own" one refcount of every buffer, and periodically scan for `refcount = 1`, at which time the GUI thread can safely delete the instance in a non-RT context (as you know delete in RT audio thread is not allowed :) 
= If multiple threads are using the buffer, make sure the refcount is atomic
- For debug purposes its usually nice having a canary before/after the data to detect overflow
- Ensure the data is cache-line aligned (for performance -> perhaps premature now..)
- It can be wrapped into a class (I hear yee guys like "very" modern C++ ;) but allow retrieving of a simple `float *` for C-based processing too (FAUST requires this for input/output usually)

Hope that helps, -Harry

**Comment by topisani** [comment]
Ive done this in the meantime
buffers are allocated once at startup in a single pool, and then use reference counting at runtime. This should be very close to the fastest possible implementation.
