### ISSUE TITLE
Synth Modulation Module

### ISSUE THREAD

**Issue by jmidt** [topisani/OTTO#53]
Let's talk about modulation. 

In synth mode, there should be a module for modulating the sound. We already have an ADSR envelope for the volume (well, it's not implemented yet, but it is a part of the Faust DSP synth files). So we really just need a screen that controls those variables. But this is our very own MOD matrix!

The following are my thoughts on what it would look like in my little dream world, so feel free to comment!

The modulation (MOD) module should contain two modulation sources: an AD envelope and an LFO. Each source has a DESTINATION (knob 1), and three parameters (knobs 2-4). You would change between controlling the two sources by perhaps an encoder click or shift+mod or something, but it should be possible to have both running at the same time

### Controls:
**AD envelope:**
1. Destination options
    - None/off
    - Synth knob 1
    - Synth knob 2
    - Synth Knob 3
    - Synth knob 4
    - LFO Speed
    - LFO Amount
2. Attack
    Determines the envelope attack time (time from starting value to maximum value). Turning it completely counterclockwise sets it to zero so it skips the attack step.
3. Decay
    Determines the envelope decay time (time from maximum value to ending value). Turning it completely clockwise sets it to infinity so it stays on the maximum value.
4. Amount (±)
   Determines the strength of the envelope. The maximum value of the envelope is always the current value of the destination. This sets the difference between that value and the value where the envelope starts and ends. It can be either positive or negative. If the Amount knob is on the counterclockwise half, the envelope starts lower and moves up to zero (the current setting of the destination). If Amount is set on the clockwise half, it starts above and moves down to zero. If Amount is directly in the middle, the envelope has no effect.

**LFO:**
1. Destination options
    - None/off
    - Synth knob 1
    - Synth knob 2
    - Synth Knob 3
    - Synth knob 4
    - Volume (tremolo)
    - Pitch (Vibrato)
2. Wave
    - Switches between different waveforms. (Triangle, Saw, Reverse Saw, Square).
3. Speed
    - Determines the speed of the LFO.
4. Amount
   - Determines the strength of the LFO. Setting it completely counterclockwise sets Amount to zero, so the LFO does not change the sound.

### Open questions:

- Should the LFO retrigger every time a key is pressed? Or be free running?

**Comment by topisani** [comment]
I think im gonna close this for now - its out of scope for at least the first version
