### ISSUE TITLE
Installation issue on macOS

### ISSUE THREAD

**Issue by amilajack** [topisani/OTTO#55]
I'm getting the following error after running `make`
```
➜  OTTO git:(master) ✗ make
[  3%] Built target imgui
[  6%] Built target nanovg
[ 11%] Built target nanocanvas
[ 14%] Built target external
[ 20%] Built target fmt
[ 41%] Built target glfw
[ 42%] Building CXX object src/CMakeFiles/otto.dir/core/audio/faust.cpp.o
warning: unknown warning option '-Wc++17-compat' [-Wunknown-warning-option]
In file included from /Users/amila/Documents/Projects/OTTO/src/core/audio/faust.cpp:1:
In file included from /Users/amila/Documents/Projects/OTTO/src/./core/audio/faust.hpp:14:
/Users/amila/Documents/Projects/OTTO/src/./util/type_traits.hpp:6:10: fatal error: 
      'variant' file not found
#include <variant>
         ^~~~~~~~~
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [src/CMakeFiles/otto.dir/core/audio/faust.cpp.o] Error 254
make[1]: *** [src/CMakeFiles/otto.dir/all] Error 2
make: *** [all] Error 2
➜  OTTO git:(master) ✗ 
```

Clang version
```
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by topisani** [comment]
did you go through this? https://github.com/topisani/OTTO/wiki/Compiling-and-Running
You need clang 5+ (not appleclang)

**Comment by amilajack** [comment]
The error:
```
/Users/amila/Documents/Projects/OTTO/src/./util/type_traits.hpp:6:10: fatal error: 'variant' file not found
#include <variant>
         ^~~~~~~~~
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
➜  OTTO git:(master) ✗ $CXX --version
clang version 5.0.1 (tags/RELEASE_501/final)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

**Comment by topisani** [comment]
Ah, seems you set CXX after running cmake the first time. You gotta kill the cmake cache using `rm -rf CMakeFiles Cmakecache.txt`. that might do the trick.

**Comment by amilajack** [comment]
That fixed it. Thanks!

**Comment by johanGelinder** [comment]
I am also having issues on mac with similar issues.
I can run `cmake .` without any isses, but when I run `make` it fails. 
Here is the output:

`Scanning dependencies of target otto
[ 33%] Building CXX object src/CMakeFiles/otto.dir/core/audio/faust.cpp.o
In file included from /Users/Johan/Documents/OTTO/src/core/audio/faust.cpp:1:
/Users/Johan/Documents/OTTO/src/./core/audio/faust.hpp:155:18: error: field type
      'otto::core::audio::FaustOptions' is an abstract class
    FaustOptions opts;
                 ^
/usr/local/include/faust/gui/UI.h:71:22: note: unimplemented pure virtual method
      'addSoundfile' in 'FaustOptions'
        virtual void addSoundfile(const char* label, const char* filenam...
                     ^
1 error generated.
make[2]: *** [src/CMakeFiles/otto.dir/core/audio/faust.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/otto.dir/all] Error 2
make: *** [all] Error 2`

Any ideas what it could be?

**Comment by topisani** [comment]
Yeah, it looks like its including your locally installed faust version, no idea why, it really shouldnt be doing that...

**Comment by johanGelinder** [comment]
Exactly.. 
Any idea of in which end I should start tackling this problem? 
Could it be a problem with how faust in installed?
I can run the faust examples without any issues with `faust2jack, so it clearly works in some kind of fashion..
