### ISSUE TITLE
Pressing Shift + Right Arrow when 0:00 goes out of the tape recorder

### ISSUE THREAD

**Issue by Axenntio** [topisani/OTTO#56]
When I'me in this state
<img width="432" alt="screen shot 2018-03-18 at 14 55 19" src="https://user-images.githubusercontent.com/18538043/37566656-a600b280-2abc-11e8-86d2-ec94a9b9a944.png">
pressing Shift + Right Arrow does this
<img width="432" alt="screen shot 2018-03-18 at 14 55 34" src="https://user-images.githubusercontent.com/18538043/37566671-bf8acb6e-2abc-11e8-8484-ce3ae18a1d2b.png">

Edit: seems that the issue is already reported on #31

**Comment by topisani** [comment]
Tapedeck has been removed - see #66
