### ISSUE TITLE
Use round instead of float for displaying panning in mixer

### ISSUE THREAD

**Issue by BandW2011** [topisani/OTTO#57]
Opening the mixer, then panning the blue or green channel left by one key press (i.e. pressing Shift + A or Shift + S to pan from "C" to "1L") doesn't display "1L" like the other channels do, but continues to display "C". Panning left again will shift the panning from "C" to "2L".

Original position of panning in each channel:
![1](https://user-images.githubusercontent.com/9336011/38943290-a5a6839e-42f6-11e8-9712-bb42c7a16677.png)

Pressing Shift + A once:
![2](https://user-images.githubusercontent.com/9336011/38943306-ae126480-42f6-11e8-851c-49e5f5dd95c5.png)

Pressing Shift + A again:
![untitled](https://user-images.githubusercontent.com/9336011/38943322-b4564258-42f6-11e8-8d50-781b4422846f.png)

**Comment by topisani** [comment]
right, this is due to flooring instead of rounding, along with floating point inaccuracies. thanks for reporting

**Comment by topisani** [comment]
Mixer has been removed - see #66
