### ISSUE TITLE
Framebuffer issue

### ISSUE THREAD

**Issue by nebularnoise** [topisani/OTTO#62]
The following code causes a segfault on my setup.
```cpp
//fbcp.cpp:21    
fbfd = open("/dev/fb1", O_RDWR);
```

`/dev/fb1` does not exist on my setup, and it caused a segfault somehow. Replacing it with `/dev/fb0` solved the segfault, as `/dev/fb0` exists.

**Comment by topisani** [comment]
We need a compile time config to disable FBCP. `OTTO_USE_FBCP` should do the trick.

It could also be done with a runtime config, probably wouldnt really be an issue.

**Comment by topisani** [comment]
fixed in 59f482b76b807a4bddb6ed67f935c2b9dd5b768f

If `OTTO_USE_FBCP` is on, then it attempts to start the FBCP, but a failure is not a crash (not sure if this is desired behaviour, but it seems like reasonable default behaviour)
