### ISSUE TITLE
macOS build error: missing `khrplatform.h`

### ISSUE THREAD

**Issue by freder** [topisani/OTTO#65]
hi,

I got stuck trying to compile `OTTO` on macOS.

```
export PATH="/usr/local/opt/llvm/bin:$PATH"

export CC=clang
export CXX=clang++
export CXXFLAGS="-I/usr/local/opt/llvm/include -I/usr/local/include"
export LDFLAGS="-L/usr/local/lib $(brew info llvm | grep LDFLAGS= | cut -d = -f 2 | tr '"' ' ')"

cmake .
make
```

↓↓↓

```
Scanning dependencies of target external
[ 18%] Building C object external/CMakeFiles/external.dir/src/gl3w.c.o
In file included from /bla/OTTO/external/src/gl3w.c:31:
In file included from /bla/OTTO/external/include/GL/gl3w.h:34:
/bla/OTTO/external/include/GL/glcorearb.h:616:10: fatal error:
      'KHR/khrplatform.h' file not found
#include <KHR/khrplatform.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [external/CMakeFiles/external.dir/src/gl3w.c.o] Error 1
make[1]: *** [external/CMakeFiles/external.dir/all] Error 2
make: *** [all] Error 2
```

there is a `khrplatform.h` file, but it's in `external/glfw/deps/KHR/khrplatform.h`.

---

`$CXX --version`:
```
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
```

**Comment by topisani** [comment]
Yep, been getting that on travis too lately. No idea why, probably my recent buildscript cleanups... maybe try comparing some older cmake files with the new ones? older means before the `boards` folder showed up

**Comment by D-I-S-K-U-S** [comment]
Cited from someone else with this error, in the discord:

> Tobias Pisani - 16-06-2018
> oh right, you gotta remove the external/src/gl3w.c file
> it gets generated for the default board, and not removed when you switched

**Comment by D-I-S-K-U-S** [comment]
the newest alpha branch should fix this :)

**Comment by topisani** [comment]
turns out it was just plain bad luck. Had nothing to do with my buildscript cleanups, but just that the glcoreapi header from khronos changed. Update the script that downloads it to also download its new dependecy

**Comment by freder** [comment]
what did it for me was:
- copy `khrplatform.h` to where it expects it to be
- rename a bunch of `.cpp` files to `.mm` (or the other way around, iirc)
- build `jack` from source
