### ISSUE TITLE
UI Redesign

### ISSUE THREAD

**Issue by topisani** [topisani/OTTO#67]
@D-I-S-K-U-S lets share a bit of progress here
Id like to do this before v0.0.1 if possible?

**Comment by D-I-S-K-U-S** [comment]
Yes, good one. I’ll update the design doc/readme as well.

**Comment by D-I-S-K-U-S** [comment]
I've updated the design guidelines, and created new issues for the specific things we needs new UI for. We can probably close this issue now, I think?
