### ISSUE TITLE
A Raspberry Pi image download

### ISSUE THREAD

**Issue by topisani** [topisani/OTTO#68]
For now just based on raspbian i think. Might take another stab at a custom distro, but whichever way we go, we need a .img download thats ready to flash on an sdcard. It should have the tools needed for development, along with a compiled binary.

**Comment by meronz** [comment]
A minimal custom distro could be made with Yocto. It allows for fast boot times and low memory footprint. Image generation is embedded and I think it could also be automated with a CI system (though generally it takes a lot of space for temporary files!). I could help with that. What do you think?

**Comment by topisani** [comment]
I have been working on it using buildroot, which i think is pretty much the same as yocto. I never got device trees to work though, that was the only issue. Also, for now its really nice to have an actual raspbian on there for development purposes. But yeah sure, if you could set it up, that would be awesome!

**Comment by DubbyLabby** [comment]
https://github.com/topisani/OTTO/issues/85

Satellite ccrma ftw!
