### ISSUE TITLE
ADSR / Envelope UI

### ISSUE THREAD

**Issue by D-I-S-K-U-S** [topisani/OTTO#72]
We need a new UI for the ADSR Envelope. 
I believe this should the most simple UI on earth. ;-)

This is the one we used to use before:
<img width="635" alt="schermafbeelding 2017-11-15 om 13 03 22" src="https://user-images.githubusercontent.com/31598745/43801330-142616d8-9a93-11e8-917b-aed6484d3d9e.png">

Any idea/concept/sketch/suggestion is welcome.

**Comment by D-I-S-K-U-S** [comment]
Can you make/sketch what you mean? I think I get what you're saying, but having an example would help getting opinions here and on the Discord going. :-)

**Comment by D-I-S-K-U-S** [comment]
So, if I got your idea right, you mean something like this?

<img width="971" alt="schermafbeelding 2018-08-09 om 19 39 49" src="https://user-images.githubusercontent.com/31598745/43915773-09e3a5a8-9c0c-11e8-82a2-550897015ad3.png">

**Comment by topisani** [comment]
i think i could be a fan of that

**Comment by zacYP2** [comment]
I love this, could also add a low opacity area under the curve?

**Comment by zacYP2** [comment]
I can do it next week too I'll have time

**Comment by zacYP2** [comment]
There you go, quick mockup
![otto adsr](https://user-images.githubusercontent.com/28604041/43950949-cba1b09c-9c5f-11e8-9521-37f14071f0e6.jpg)

**Comment by zacYP2** [comment]
Maybe we should drop the tail of the release? the fact that it has no area shows it's not representing anything.

**Comment by zacYP2** [comment]
This maybe?

![otto adsr 2](https://user-images.githubusercontent.com/28604041/43951145-4f72a58e-9c60-11e8-808b-2e8d6f3acf7d.jpg)

**Comment by nebularnoise** [comment]
IMHO the Release should be curved like the Decay. Other than that, I'm a fan 👍

**Comment by cester-ino** [comment]
In reality in a envelope editor you should be able to set the curves trend, maybe via a keys combination (i.e. Fn+encoder)

**Comment by nebularnoise** [comment]
Maybe by pressing the red or blue encoder ?

**Comment by cester-ino** [comment]
I think it would be better if we set a standard for accessing Alt-settings (i.e. Holding shift or Fn) this way you can set more than 4 parameters in any function)

**Comment by topisani** [comment]
trend?

**Comment by topisani** [comment]
Could maybe be interesting to do. I think id prefer just doing exponential curves and be done with it though

**Comment by D-I-S-K-U-S** [comment]
I evolved on zacYP2's idea and added the fill below the ADSR lines. I put some black in between the blocks to prevent contrast issues and clutter though. 

I personally really like where this is going!

<img width="636" alt="schermafbeelding 2018-08-13 om 23 54 49" src="https://user-images.githubusercontent.com/31598745/44080499-806bc82e-9fac-11e8-95bc-224a580ed86b.png">

**Comment by zacYP2** [comment]
Good work! Something feels off with the roudned corners, it does not make the yellow and blue part seem continuous. Is there any way the junctions could feel more pointy without taking away the black space? I don't have the awnser, just the question :P

**Comment by D-I-S-K-U-S** [comment]
Well, to be fair (and it might be an unpopular opinion); the ADSR is not specifically about having a continuous line, but it is about showing the differences of the settings between A, D, S, and R. So in the view of the users experience, separating those values is a gain, as it becomes easier to make distinction between the values., without having to look at it too long. Now, I know colour has this property, too, but having both a space in between and the colour coding, it makes it really user friendly and quick in use.

Is my two cents. 

But we'll have to see how it functions in real life situation to make up a verdict, I think.

**Comment by zacYP2** [comment]
Good point. I agree we should keep rounded corners. I am eager to see it in action now!

**Comment by zacYP2** [comment]
Is there a way to integrate opacity for the area under the curve? I am not sure how it would work with the display or how it fits with the graphical identity of the project, but it could be worth a try. Can you try a mockup with what you did DISKUS?

**Comment by topisani** [comment]
We tried opacity too, definately doesnt fit in.

To be honest, we're not gonna change anything about this. We really like it, and it fits in very well with our style - lets move on to other things
