### ISSUE TITLE
Step sequencer

### ISSUE THREAD

**Issue by AlbertSmit** [topisani/OTTO#73]
We need new UI for a (step) sequencer. So mind you, it doesn't specifically need to be a step sequencer. Don't let that limit you. :-)

Anything goes, and anything is welcome.

Good luck!

**Comment by topisani** [comment]
#78, The euclidian sequencer is aimed for alpha, so maybe we hold off on another one?

Taking this out of alpha so far, if someone comes up with a design for another sequencer post it here, and we'll discuss it

**Comment by zacYP2** [comment]
Some inspiration

![polyrhytmus](https://user-images.githubusercontent.com/28604041/44304295-40708200-a326-11e8-9279-ac3eec899513.gif)
