### ISSUE TITLE
Thibault's RingMod DSP UI

### ISSUE THREAD

**Issue by AlbertSmit** [topisani/OTTO#74]
We need UI for Thibault's DSP.

It's a Ring Modulator inspired by a 'stompbox' called Shallow Water. Hence, a new name would also be a welcome addition. Thibault should probably have the final word in picking a name for it though, as he created the DSP (is my opinion).

> Quick explanation (by Thibault):
>
> **LPG**: Cutoff frequency of an enveloppe-follower modulated low pass filter. (low settings will make the effect darker and more expressive, high settings make the filtering more transparent and subtle)
>
> **Rate**: Speed of pitch modulation (from imperceptibly modulated to audio-rate pitch modulation)
>
> **Depth**: Depth of pitch modulation (high settings for very crazy, low settings for chorusey, tape wobbley effect)
>
> **Damp**: Smoothes the pitch modulation (makes it less steppy and more wavey)

This is something I came up with; feel free to evolve this design, or create anything new. Open to all suggestions.

![otto2-02](https://user-images.githubusercontent.com/31598745/43801618-edf48ee4-9a93-11e8-9d13-deff655c4baf.jpg)

And these are iterations/versions/animations of the same design:
![otto2-03](https://user-images.githubusercontent.com/31598745/43801649-fee2f650-9a93-11e8-8a7f-986911343235.jpg)

Cheers!

**Comment by LudicrouSpeed** [comment]
Dude, I absolutely love the look of these graphics.

**Comment by topisani** [comment]
@AlbertSmit If you have time at some point, id love to see an implementation of this one!
but, @nebularnoise would probably need to rewrite it to gamma, as we want to get away from faust
