### ISSUE TITLE
Onboarding Process Feedback

### ISSUE THREAD

**Issue by mross1080** [topisani/OTTO#75]
Just went through the onboarding process, just have two pieces of feedback 

1. In https://github.com/topisani/OTTO/wiki/Compiling-and-Running for MAC OSX the instructions say that CLang version should be something like 5.0.0, but the instructions actually end up installing 6.0.1 (could be useful to update the expected output) 
2. In the https://github.com/topisani/OTTO/wiki/Compiling-and-Running#build, there is a missing step to actually run the Jackd server.  The setup has you put preferences in `~/.jackdrc` but is missing a step in the build to actually start it up.  

Everything else went perfectly!

**Comment by SallySoul** [comment]
I'm on macOS 10.14.2.

I also had to install `glfw` with brew

```
brew install glfw
```

And to clarify mross1080's second point for anyone looking for help, you need to run the 'JackPilot' application, then hit the start button. I couldn't find a way to run the jack server via the command line.

**Comment by topisani** [comment]
A lot of this has changed in the meantime
