### ISSUE TITLE
Pressure/Velocity sensitive buttons/keys

### ISSUE THREAD

**Issue by cb88** [topisani/OTTO#79]
Just ask anyone that has every played an electronic instrument, pressure sensitive buttons is a huge feature. It's a feature missing from the OP-1.

Even if it was just a single one it would help a lot though all being force sensitive would be preferable.

Force sensitive resistors might be a good fit.
http://www.codetinkerhack.com/2013/01/how-to-add-velocity-aftertouch-midi.html

**Comment by topisani** [comment]
We support velocity from an external input already, and since there is _no_ "official" otto hardware, there is no issue with someone building one supporting velocity.
