### ISSUE TITLE
Post a video and soundfile

### ISSUE THREAD

**Issue by E3V3A** [topisani/OTTO#80]
This "look" like agreat project, but without a video or playable sound file of what this project can do right now, its...eh kind of hard to tell. So please upload something to listen to.

**Comment by D-I-S-K-U-S** [comment]
Hi E3V3A (or is it E:V:A? Not sure)!

I see what you mean, thank you for sharing that.

We are currently working on getting an Alpha version out.
When the Alpha is released, we're _planning_ to release demonstration video's of that.

I don't think we discussed uploading sound samples/files, but that's actually a pretty cool idea.
We'll take that into consideration! Once again, thanks for sharing!

Cheers!

(- Albert)
