### ISSUE TITLE
Keep getting stuck at cloning the OTTO repo and building

### ISSUE THREAD

**Issue by jacm-k** [topisani/OTTO#81]
I get to `git checkout develop-topisani` and everythings fine except when i input `rm external/src/gl3w.c` it says "rm: cannot remove 'external/src/gl3w.c': No such file or directory".
I also tried `cmake -DOTTO_BOARD=rpi-proto-1 -DOTTO_USE_LIBCXX=ON .` but I get an error instead:

> pi@raspberrypi:~/dl/cmake-3.12.0-rc1/jack2/OTTO $ cmake -DOTTO_BOARD=rpi-proto-1 -DOTTO_USE_LIBCXX=ON
> Using libc++ instead of libstdc++
> -- CMake version: 3.12.0-rc1
> CMake Deprecation Warning at external/fmt/CMakeLists.txt:6 (cmake_policy):
>   The OLD behavior for policy CMP0048 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> 
> -- Version: 4.0.1
> -- Build type: 
> CMake Error at external/GSL/CMakeLists.txt:26 (message):
>   The compiler /usr/bin/c++ has no C++14 support.  Please use a different C++
>   compiler.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/pi/dl/cmake-3.12.0-rc1/jack2/OTTO/CMakeFiles/CMakeOutput.log".
> See also "/home/pi/dl/cmake-3.12.0-rc1/jack2/OTTO/CMakeFiles/CMakeError.log".

I've restarted fresh 3 times and I'm not really sure where I went wrong.

**Comment by jacm-k** [comment]
What about the `cmake -DOTTO_BOARD=rpi-proto-1 -DOTTO_USE_LIBCXX=ON .` command? I've tried to use make after that but all I get is:

> make: *** No targets specified and no makefile found.  Stop.

**Comment by lufiaraujo** [comment]
Wait! What did you do to make it work???

**Comment by jacm-k** [comment]
first i used the code from jpegsarebad:

```
echo 'export CXX=clang++ CC=clang' >> ~/.bashrc
source ~/.bashrc
rm -rf CMakeCache.txt CMakeFiles
cmake -DOTTO_BOARD=rpi-proto-1 -DOTTO_USE_LIBCXX=ON
```

then it worked a bit then not so i restarted by:

```
cd ~/dl/cmake-3.12.0-rc1/jack2/
rm -r OTTO
sudo mandb
eval "$(ssh-agent -s)
git clone git@github.com:topisani/OTTO.git
cd OTTO/
git checkout develop-topisani
cmake -DOTTO_BOARD=rpi-proto-1 -DOTTO_USE_LIBCXX=ON .
```

and got past that stage.

use '&&' to do it all at once
`cd ~/dl/cmake-3.12.0-rc1/jack2/ && rm -r OTTO && sudo mandb`..... etc
