### ISSUE TITLE
So close yet so far can't seem to "make" the OTTO

### ISSUE THREAD

**Issue by jacm-k** [topisani/OTTO#82]
I was able to fix the previous command but as soon as I run `make` I get a few errors

> pi@raspberrypi:~/dl/cmake-3.12.0-rc1/jack2/OTTO $ make
> [  4%] Built target tiny-process-library
> [  9%] Built target imgui
> [ 12%] Built target nanovg
> [ 18%] Built target nanocanvas
> [ 21%] Built target external
> [ 29%] Built target fmt
> [ 31%] Building CXX object src/CMakeFiles/otto.dir/__/boards/parts/ui/egl/src/egl_ui.cpp.o
> /home/pi/dl/cmake-3.12.0-rc1/jack2/OTTO/boards/parts/ui/egl/src/egl_ui.cpp:45:32: error: no member named 'WIDTH' in namespace 'otto::core::ui::vg'
>     vg::Canvas canvas(nvg, vg::WIDTH, vg::HEIGHT);
>                            ~~~~^
> /home/pi/dl/cmake-3.12.0-rc1/jack2/OTTO/boards/parts/ui/egl/src/egl_ui.cpp:45:43: error: no member named 'HEIGHT' in namespace 'otto::core::ui::vg'
>     vg::Canvas canvas(nvg, vg::WIDTH, vg::HEIGHT);
>                                       ~~~~^
> /home/pi/dl/cmake-3.12.0-rc1/jack2/OTTO/boards/parts/ui/egl/src/egl_ui.cpp:52:52: error: no member named 'WIDTH' in namespace 'otto::core::ui::vg'
>     float xscale = egl.draw_size.width / float(vg::WIDTH);
>                                                ~~~~^
> /home/pi/dl/cmake-3.12.0-rc1/jack2/OTTO/boards/parts/ui/egl/src/egl_ui.cpp:53:53: error: no member named 'HEIGHT' in namespace 'otto::core::ui::vg'
>     float yscale = egl.draw_size.height / float(vg::HEIGHT);
>                                                 ~~~~^
> /home/pi/dl/cmake-3.12.0-rc1/jack2/OTTO/boards/parts/ui/egl/src/egl_ui.cpp:87:65: error: no member named 'HEIGHT' in namespace 'otto::core::ui::vg'
>         canvas.fillText(fmt::format("{:.2f} FPS", fps), {0, vg::HEIGHT});
>                                                             ~~~~^
> 5 errors generated.
> src/CMakeFiles/otto.dir/build.make:426: recipe for target 'src/CMakeFiles/otto.dir/__/boards/parts/ui/egl/src/egl_ui.cpp.o' failed
> make[2]: *** [src/CMakeFiles/otto.dir/__/boards/parts/ui/egl/src/egl_ui.cpp.o] Error 1
> CMakeFiles/Makefile2:99: recipe for target 'src/CMakeFiles/otto.dir/all' failed
> make[1]: *** [src/CMakeFiles/otto.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by D-I-S-K-U-S** [comment]
I believe, from seeing the progress in the Discord, this is solved now? @topisani ?

**Comment by topisani** [comment]
It is, updates are in the newest master
