### ISSUE TITLE
Engine generation (bash)script

### ISSUE THREAD

**Issue by jmidt** [topisani/OTTO#87]
I have written DSP for a simple synthesizer with 4 controls. I was thinking of including this in the alpha, but in the developer build. So it is not a part of the 'real' alpha, but will be there for developers to have a simple way of seeing how the DSP should be written and how it connects with the backend and how UI is made.

I want to do the same thing with an effect, probably something like a volume and pan and then two other things. Suggestions are welcome!

UI should simply be text with numbers. Very simple.

**Comment by topisani** [comment]
Maybe a better way to do it is an engine generation script, which generates the boilerplate for new engines, inserting some default code.

If you write these extremely simple engines, I'll write a generation script

**Comment by jmidt** [comment]
When you say simple, do you mean something that uses a minimum of available features, or something that shows off all the features, but in a minimal way? If that makes sense...

**Comment by topisani** [comment]
Have them, but make the functions empty

**Comment by jmidt** [comment]
This is now in the hotfix/engine-polish branch.

**Comment by jmidt** [comment]
Updated. Added **GFI** flair.

**Comment by topisani** [comment]
Try out the one added in 174d521cc2c627382a5e8e9f403fc489ee2fa377
The templates could be cleaned up a little bit, and there should be one for arp engines, but this is something at least
