### ISSUE TITLE
32 keys

### ISSUE THREAD

**Issue by naught101** [topisani/OTTO#88]
In the current versions, the proposed key layouts look like this:

![keys_25](https://user-images.githubusercontent.com/167164/44502064-1ecf1c00-a6d3-11e8-9b65-52fb6dae0035.png)

If you added a handful more keys, you could have 32 keys:

![keys_32](https://user-images.githubusercontent.com/167164/44502086-35757300-a6d3-11e8-9360-2f098972eae7.png)

This would make sequencing MUCH easier, without taking up much more space. Sequencing on the OP-1 is one of the most difficult things about the device, IMO, and this would get around a lot of that.

The white keys on the top row could provide other functionality (pitch bend? Octave shifting?), or they could just be dead when in keyboard mode .

**Comment by nebularnoise** [comment]
Man, if 8 is a handful in your book, I worry about your hands ;)

Jokes aside, it is an interesting idea, but I don't like the white keys in between the black one honestly.

I'd rather add two keys only on either side of the lower row, making the keyboard go from B1 to C4.
We'd then have 16 keys on the lower row, and sequencing could be done with these 16 lower keys, and some paging.

**Comment by naught101** [comment]
The top row white keys could be another colour like grey, the colour of the device body.
 
But yeah, 16 would also be good, and then the top row could be extra function keys when in sequencer mode (like bar select, for multi-bar patterns).

**Comment by nebularnoise** [comment]
Sequencing like that would benefit a lot from having individually backlit keys. That would require and LED matrix on top of the switch matrix, so probably a third pro micro (at least for prototyping)

**Comment by naught101** [comment]
Yeah, that would be awesome.

Also, it probably should be in its own issue, but velocity sensitivity ([something like this](https://www.youtube.com/watch?v=KfjEYu79J-4))  for the keyboard keys would be really awesome. Expression is something lacking in the OP-1.

**Comment by E3V3A** [comment]
HAving buttons as "piano" keys, look so cheap. 
How about getting some something like [this](https://www.alibaba.com/product-detail/Hot-Selling-Musical-Keyboard-Mini-Electronic_60767526181.html?spm=a2700.7724857.normalList.105.11543869cRxE4m): 

![hot-selling-musical-keyboard-mini-electronic-piano](https://user-images.githubusercontent.com/194392/44623131-00c21100-a8b7-11e8-8abc-15d0dd36288b.jpg)

**Comment by topisani** [comment]
We have a more set in stone hardware layout now.

**Comment by naught101** [comment]
The one like the images on the front page?

**Comment by topisani** [comment]
nope - some renders and updates will follow - check out the [roadmap on the wiki](https://github.com/topisani/OTTO/wiki/Roadmap) for now
