### ISSUE TITLE
FM Synth UI idea

### ISSUE THREAD

**Issue by nebularnoise** [topisani/OTTO#90]
So, I was chatting in the discord with thblackhelmetman about an FM synth.

thblackhelmetman showed a drawing of a UI which would allow for a modular amount of operators, but I think a fixed number of operators is the way to go, for two reasons:

1. It caps the CPU usage (no risk of throttling the raspi cpu because of too many operators in the chain)
2. It makes the workflow much more straightforward

I think the most natural number of operatos would be four, one for each encoder colour. As for the algorithms, it would be selectable in a secondary menu, and the full list for four operators has already been established in Ableton Live's Operator:
![FM Algorithms](http://www.sequencer.de/pix/ableton/FM-bass_tutorial1.gif)

Here's what I came up with:
![fm_ui_idea](https://user-images.githubusercontent.com/33561374/44525352-01a14a00-a6e1-11e8-878b-7cb875f5f10d.png)
The idea behind the shapes is to imply the waveshape:

- Circle for sine wave
- Square for square wave
- Triangle for triangle wave
- Sharp star kinda box for saw wave

The number is the operator volume/modulation amount. Above, the triangle is dotted because the blue operator is deactivated (volume==0).  I also admit I did not put the text in the triangle because the alignment seemed off 😅

**Comment by topisani** [comment]
The FM synth has gotten a UI in the meantime
