### ISSUE TITLE
(The synth formerly known as nuke) UI

### ISSUE THREAD

**Issue by jmidt** [topisani/OTTO#91]
We need new UI for the synth to be included in the alpha. The controls are:

Wave: Chooses the waveform. We have this animated, so including a visual representation of this would be possible and appreciated. This is the green wave in the upper left corner of the current synth UI

Relationship: Changes the relationship between the two main oscillators. Can e.g. detune slightly, and put them a fifth apart.

Aux: Does several things, but can introduce white noise and unison and sub oscillators.

Filter: A low-pass filter. Currently with two different choices of resonance, although this might be taken out if we can't find a good way to visualize it.

**Comment by ejmason101** [comment]
https://www.youtube.com/watch?v=NTTxmc1ue08

**Comment by topisani** [comment]
There is one now - the implementation is not fully completed though, so that still has to be done

**Comment by topisani** [comment]
The synth is gone for now anyway
