### ISSUE TITLE
Brickwall limiter

### ISSUE THREAD

**Issue by nebularnoise** [topisani/OTTO#93]
⚠️ Disclaimer ⚠️ I have not tested this code 😅 
But as far as my ~~ears~~ eyes can tell, it looks fine. On a more serious note, I could only briefly test it on the online faust editor with a dodgy setup. If anyone can confirm of finesse this code, it'd be greatly appreciated.

```cpp
import("stdfaust.lib");
ratio = 1000; // effectively infinity
att = 0.10 / 1000; // 0.10ms
rel = 200 / 1000; // 200ms 
thresh = hslider("thresh",0,-70,0,0.001) : si.smoo; // compressor threshold in dB
gain = ba.db2linear(-thresh-1); // automatic makeup gain. one dB less than thres for safety
process = _,_ : co.compressor_stereo(ratio,thresh,att,rel) : *(gain), *(gain) : _,_;
```

Ratio, attack and release constants might need some tweaking to get the right feel.
I arbitrarily chose -70dB as my lowest threshold value, it is debatable.

**Comment by jmidt** [comment]
Master compressor has been implemented.
