### ISSUE TITLE
[Sampler] Overview

### ISSUE THREAD

**Issue by jmidt** [topisani/OTTO#99]
Mission statement:
A sampler that functions well with both drum-like samples, as well as pitched samples such as a sampled piano.
Use should be both flexible/general, but allow for easy tweaking of individual samples and changing which samples are loaded.

Fundamental idea:
Implemented as an 'Instrument' engine, there exists up to 66 sample slots, one for each midi key one might use. One sample file is loaded into each sample shot and is played when the midi note is received. The last played note is considered the 'current' sample, is displayed on the screen, and can be edited using the encoders.

**Comment by jmidt** [comment]
For recording samples, I agree that it should be kept in mind how it would interface. But thinking modularly, I whould implemet this as an entirely separate thing.

I also agree that there IS an advantage to not having that much granular control. It would definitely make designing it a lot easier. But this is in essence just the OP1 sampler again - with separate files instead of appended samples in one file. 
Also, then the question of recording samples comes back - how would a newly recorded sample fit in with the fact that you only have control over which sample pack is loaded? Should you choose a sample slot to swap with in some sample pack?

**Comment by jmidt** [comment]
But what then if you are only interested in sampling a single sound that
you heard? If you always sample an entire pack, you would have to have all
sounds you need recorded in one go, no?

fre. 19. okt. 2018 06.26 skrev Tobias Pisani <notifications@github.com>:

**Comment by topisani** [comment]
Im considering closing these, as the new design has quite different requirements, what do you think @jmidt
